In [ ]:
QUESTION 1

In [ ]:
 A F&B manager wants to determine whether there is any significant difference in 
the diameter of the cutlet between two units. A randomly selected sample of cutlets 
was collected from both units and measured? Analyze the data and draw inferences at 5% significance level.
Please state the assumptions and tests that you carried out to check validity of the assumptions.


In [2]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [3]:
data=pd.read_csv('Cutlets.csv')
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [4]:
unitA=pd.Series(data.iloc[:,0])
unitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [5]:
unitB=pd.Series(data.iloc[:,1])
unitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [6]:
p_value=stats.ttest_ind(unitA,unitB)
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [7]:
p_value[1] 

0.4722394724599501

In [ ]:
Because the p-value of our test (0.4722394724599501) is greater than alpha = 0.05,
we fail to reject the null hypothesis of the test. 
There is no difference in diameters of cutlets between two units

In [ ]:
QUESTION 2

In [ ]:
A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) 
of reports of the laboratories on their preferred list. They collected a random sample and recorded 
TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
  Analyze the data and determine whether there is any difference in average TAT among the different 
laboratories at 5% significance level.
 
 
    Minitab File: LabTAT.mtw

In [8]:
labtat = pd.read_csv('LabTAT.csv')
labtat.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [9]:
labtat.describe()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [10]:
test_statistic , p_value = stats.f_oneway(labtat.iloc[:,0],labtat.iloc[:,1],labtat.iloc[:,2],labtat.iloc[:,3])
print('p_value =',p_value)

p_value = 2.1156708949992414e-57


In [ ]:
pvalue>0.05 so choose null hypothesis & reject alternate hypothesis

In [ ]:
QUESTION 3

In [ ]:
 test with Contingency table
We need to check whether the proportion of any of these samples are different or the same?

Step 1

Make two Hypothesis one contradicting to other
Null Hypothesis is want we want to prove

Null Hypothesis: There is no association or dependency between the gender based buyer rations across regions
    
Alternative Hypthosis: There is a significant association or dependency between the gender based buyer rations across regions
Step 2

Decide a cut-off value
Significance 5%
alpha = 0.05
As it is a one-tailed test
alpha = 1-0.95 = 0.05
Step 3

Collect evidence
Importing Files

In [11]:
buyer = pd.read_csv('BuyerRatio.csv', index_col = 0)
buyer

East  West  North  South
Observed Values                          
Males              50   142    131     70
Females           435  1523   1356    750

In [12]:
table = [[50,142,131,70],
        [435,1523,1356,750]]

In [13]:
stat, p, dof, exp = stats.chi2_contingency(buyer) 
print(stat,"\n", p,"\n", dof,"\n", exp)

1.595945538661058 
 0.6603094907091882 
 3 
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [14]:
stats.chi2_contingency(table) 

Chi2ContingencyResult(statistic=1.595945538661058, pvalue=0.6603094907091882, dof=3, expected_freq=array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [15]:
observed = np.array([50, 142, 131, 70, 435, 1523, 1356, 750])
expected = np.array([42.76531299,  146.81287862,  131.11756787, 72.30424052, 442.23468701, 1518.18712138, 1355.88243213, 747.69575948])


In [16]:
statistics, p_value = stats.chisquare(observed, expected, ddof = 3)
print("Statistics = ",statistics,"\n",'P_Value = ', p_value)

Statistics =  1.5959455390914483 
 P_Value =  0.8095206646905712


In [ ]:
We fail to reject Null Hypothesis because of lack evidence. 
Therefore, there is no association or dependency between male-female buyers rations 
and are similar across regions. Hence, Independent samples

In [ ]:
QUESTION 4

In [ ]:
TeleCall uses 4 centers around the globe to process customer order forms. 
They audit a certain %  of the customer order forms. 
Any error in order form renders it defective and has to be reworked before processing.  
The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% 
significance level and help the manager draw appropriate inferences

Minitab File: CustomerOrderForm.mtw

In [19]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency


In [20]:
data=pd.read_csv('Costomer+OrderForm.csv')
data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [21]:
data.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [22]:
data.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [23]:
data.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [24]:
data.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [25]:
obs=np.array([[271,267,269,280],[29,33,31,20]])
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [26]:
chi2_contingency(obs)

Chi2ContingencyResult(statistic=3.858960685820355, pvalue=0.2771020991233135, dof=3, expected_freq=array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]]))

In [ ]:
As (p_value = 0.2771) > (α = 0.05); Accept Null Hypthesis i.e. Independence of categorical variables Thus, 
customer order forms defective % does not varies by centre.